const tstMenuData = 
'{'
'    "imageLogo": "assets/images/HiQLogo.png",'
'    "menuItems": {'
'        "menuItem": ['
'            {'
'                "id": "home",'
'                "label": "MenuItem1",'
'                "icon": "home",'
'                "isDefault": true'
'            },'
'            {'
'                "id": "about",'
'                "label": "MenuItem2",'
'                "icon": "info"'
'            },'
'            {'
'                "id": "services",'
'                "label": "MenuItem3",'
'                "icon": "design_services"'
'            },'
'            {'
'                "id": "contacts",'
'                "label": "MenuItem4",'
'                "icon": "contact_page"'
'            }'
'        ]'
'    }'
'}';

const tstHomeData = 
'{'
'    "header_1": "tstHomeData header_1",'
'    "header_2": "tstHomeData header_2",'
'    "content": "tstHomeData content"'
'}';

const tstAboutData =
'{'
'    "header_1": "appAboutData header_1",'
'    "header_2": "appAboutData header_2",'
'    "header_3": "appAboutData header_3",'
'    "verticalText": "appAboutData vertical text",'
'    "textBlocks": {'
'        "textBlock": ['
'            {'
'                "header": "textBlock header 1",'
'                "body": "textBlock body 1"'
'            },'
'            {'
'                "header": "textBlock header 2",'
'                "body": "textBlock body 2"'
'            },'
'            {'
'                "header": "textBlock header 3",'
'                "body": "textBlock body 3"'
'            }'
'        ]'
'    }'
'}';
